In [1]:
import numpy as np
steps = np.array([3191, 230, 9193, 4670, 164, 3820, 9093])
print(np.min(steps))
print(np.max(steps))
print(np.sum(steps))
print(round(np.average(steps), 2))

164
9193
30361
4337.29


In [2]:
month_results = np.array([56, 100, 33, 0, 45, 45, 46, 34, 89, 180, 60, 45, 45, 44, 46, 45, 0, 0, 15, 90, 301, 197, 20, 60, 45, 45, 42, 45])
print(month_results.reshape(4,7))

[[ 56 100  33   0  45  45  46]
 [ 34  89 180  60  45  45  44]
 [ 46  45   0   0  15  90 301]
 [197  20  60  45  45  42  45]]


In [3]:
month_results = np.array([56, 100, 33, 0, 45, 45, 46, 34, 89, 180, 60, 45, 45, 44, 46, 45, 0, 0, 15, 90, 301, 197, 20, 60, 45, 45, 42, 45])
print(month_results.shape)

(28,)


In [5]:
import numpy as np 
halley_commet = np.arange(start=1986, stop=3000, step=75)
print(halley_commet)

[1986 2061 2136 2211 2286 2361 2436 2511 2586 2661 2736 2811 2886 2961]


In [3]:
import numpy as np

passengers = np.array([
   [1, 0, 3, 22],
   [2, 1, 1, 38],
   [3, 1, 3, 26],
   [4, 1, 1, 35],
   [5, 0, 3, 35],
   [6, 0, 3, 18],
   [7, 0, 1, 54],
   [8, 0, 3, 2],
   [9, 1, 3, 27],
  [10, 1, 2, 14],
  [11, 1, 3, 4],
  [12, 1, 1, 58],
  [13, 0, 3, 20],
  [14, 0, 3, 39],
  [15, 0, 3, 14],
  [16, 1, 2, 55],
  [17, 0, 3, 2],
  [18, 1, 2, 12],
  [19, 0, 3, 31],
  [20, 1, 3, 8],
  [21, 0, 2, 35],
  [22, 1, 2, 34],
  [23, 1, 3, 15],
  [24, 1, 1, 28],
  [25, 0, 3, 8],
  [26, 1, 3, 38],
  [27, 0, 3, 2],
  [28, 0, 1, 1],
  [29, 1, 3, 5],
  [30, 0, 3, 18],
  [31, 0, 1, 40],
  [32, 1, 1, 70],
  [33, 1, 3, 33],
  [34, 0, 2, 66],
  [35, 0, 1, 28],
  [36, 0, 1, 42],
  [37, 1, 3, 5],
  [38, 0, 3, 18],
  [39, 0, 3, 18],
  [40, 1, 3, 14],
  [41, 0, 3, 40],
  [42, 0, 2, 27],
  [43, 0, 3, 29],
  [44, 1, 2, 0],
  [45, 1, 3, 19],
  [46, 0, 3, 33],
  [47, 0, 3, 14],
  [48, 1, 3, 22],
  [49, 0, 3, 41],
  [50, 0, 3, 18]
])

# 1) Shape
print("Shape:", passengers.shape)

# 2) Min + Max age
ages = passengers[:, 3]
print("Min age:", ages.min())
print("Max age:", ages.max())

# 3) Average age
print("Average age:", np.average(ages))

# 4) Total survivors (sum of column 1)
survivors = passengers[:, 1].sum()
print("Total survivors:", survivors)

# 5) Survival percentage
survival_percent = np.average(passengers[:, 1]) * 100
print("Survival %:", survival_percent)

# 6) np.arange + reshape demo (make 1-50 into a 5x10 grid)
ids = np.arange(1, 51).reshape(5, 10)
print("IDs reshaped (5x10):")
print(ids)

Shape: (50, 4)
Min age: 0
Max age: 70
Average age: 25.5
Total survivors: 22
Survival %: 44.0
IDs reshaped (5x10):
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]
