In [1]:
import numpy as np
steps = np.array([3191, 230, 9193, 4670, 164, 3820, 9093])
print(np.min(steps))
print(np.max(steps))
print(np.sum(steps))
print(round(np.average(steps), 2))

164
9193
30361
4337.29


In [2]:
month_results = np.array([56, 100, 33, 0, 45, 45, 46, 34, 89, 180, 60, 45, 45, 44, 46, 45, 0, 0, 15, 90, 301, 197, 20, 60, 45, 45, 42, 45])
print(month_results.reshape(4,7))

[[ 56 100  33   0  45  45  46]
 [ 34  89 180  60  45  45  44]
 [ 46  45   0   0  15  90 301]
 [197  20  60  45  45  42  45]]
